name: Update GitHub Actions

on:
  workflow_dispatch:

  # Weekly on Mondays at 10 AM UTC
  schedule:
    - cron: "0 10 * * 1"

jobs:
  update-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary GitHub App Token
        id: app
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Update GitHub Actions
        uses: alchemaxinc/update-deps/actions@v1
        with:
          token: ${{ steps.app.outputs.token }}
          app-slug: ${{ vars.BOT_APP_SLUG }}
          auto-merge: "true"
          base-branch: "main"
          prefixes: "actions"
          file-glob: ".github/**/*.yml"
          branch-prefix: "update-actions"
          pr-title: "chore: Update GitHub Actions"
          commit-message: "chore: update github actions"
